### ISSUE TITLE
Private Yahoo Group Links

### ISSUE THREAD

**Issue by Linell** [jonesnc/useful-powerschool-links#1]
The ["how to join a subquery"](https://github.com/jonesnc/useful-powerschool-links#powerquery) [link](https://groups.yahoo.com/neo/groups/PSUG/conversations/messages/144864) is restricted to being a member of a Yahoo Group. I've attempted to join, but it would be useful to have some sort of way to link the content _without_ having to join the group.

**Comment by jonesnc** [comment]
@Linell If you know of a PowerSource article that explains the same thing, I could change the link to that (or you could open a PR with the link changed). The Yahoo Group (`PSUG`) is a pretty great resource, so I'd recommend becoming a member if you haven't yet.

I've had issues with sharing documentation for PowerSchool in the past, so I probably won't be moving the content of the linked post to some other platform until I get express permission from a PowerSchool employee.

**Comment by Linell** [comment]
👍 

I've been accepted into the group, so that works. I understand not being able to move the advice into another platform.
